### ISSUE TITLE
API docs Bow brand styling

### ISSUE THREAD

**Issue by calvellido** [bow-swift/bow#120]
Current [API docs](https://bow-swift.io/api-docs/) are styled following default Apple Jazzy theme. We could align api-docs pages to the rest of the Bow branding by creating a custom theme, following Jazzy specs:

https://github.com/realm/jazzy/tree/master/lib/jazzy/themes

**Comment by juanpedromoreno** [comment]
Same here @calvellido , we need to use the available templates for this kind of goals. If none of the existent fit very well, let's create new ones. We specifically need the metadata posted in those templates ;)

Additionally, it needs to be added to the project and a proper milestone.

Thanks.
