### ISSUE TITLE
Fix "Install in Dash" from docs

### ISSUE THREAD

**Issue by truizlop** [bow-swift/bow#128]
## Description

The API docs show a button on the top bar to install docs in Dash. However, the URL seems to be wrong and it causes a problem when you try to install it.

## Expected outcome

Clicking in `Install in Dash` in the API docs page should install the docs.

## Observed outcome

A file is downloaded but has wrong contents, so the docs do not install properly.

## Possible fix

The script we use to generate the docs has a flag for `jazzy` to point out the URL that Dash uses. We need to find out which is the correct URL for that to work.

**Comment by calvellido** [comment]
While the URL can be fixed easily through the use of `--dash_url`, there will still be a problem, and it is that the XML referencing the docset contains an incorrect path that I'm not able to see how to update at the moment:

https://github.com/bow-swift/bow/blob/gh-pages/api-docs/docsets/Bow.xml

There's a `--docset-path` option which lets you generate the docset wherever you want to, but the XML there will keep pointing to the same URL, which makes this param a bit useless.

Unless a fix is sent to Jazzy the only solution I see now is to overwrite the XML manually.

**Comment by truizlop** [comment]
When I wrote the ruby script, the Dash button was only appearing if I specified the flag `--root-url`. Perhaps there is some tweaking to be done here. I'll check what combination of values we should provide to generate this properly.
