### ISSUE TITLE
Move encrypted env var to Travis repo settings

### ISSUE THREAD

**Issue by calvellido** [bow-swift/bow#131]
According to https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings, secret environment variables that are the same across all branches and builds should be set in the repository settings, not in the `.travis.yml`

My understanding is that the [current env var](https://github.com/bow-swift/bow/blob/master/.travis.yml) set in the `travis.yml` file is the one necessary to publish into CocoaPods, which will be the same across all branches and builds.

It could be a good idea if we move that var into Travis settings.

**Comment by truizlop** [comment]
Closing this, as we are moving out of Travis.
