### ISSUE TITLE
General docs site generation automation

### ISSUE THREAD

**Issue by calvellido** [bow-swift/bow#133]
While we completed API docs generation through #130, we now need to do the same for the general doc pages.

For this, a coordinated work between [nef](https://github.com/bow-swift/nef) tool, Jekyll structure generation and Travis scripts is needed.

**Comment by calvellido** [comment]
By the way, you need to head to http://localhost:4000/docs to properly see the (_suspiciously similar to Arrow_) docs layout once running.

**Comment by miguelangel-dev** [comment]
Great! It is sound good. Thank you so much - I will reply you if I have any doubts :):)

**Comment by calvellido** [comment]
Closed through #182 and #221
