### ISSUE TITLE
Search bar malfunctioning

### ISSUE THREAD

**Issue by truizlop** [bow-swift/bow#138]
## Description

There are some of issues that I have experienced using the search bar:

1) Type `Either`. It does not show on the suggestion list. Hitting enter does not navigate to its docs.
2) Searching from a page different from the main one sometimes leads to 404 errors. An example flow to reproduce it:
- Go to the main page for API docs.
- Type `Lens` in the search bar. Three results `[Lens, Lens, LensPartial]` show.
- Click on the first result and navigate to that page.
- While you are on the `Lens` page, type `Lens` on the search bar again.
- Select the second `Lens` result.
- You should see a 404.

I think this is due to a bad formatting of the URL. Looking at the address bar, it says `https://bow-swift.io/api-docs/Extensions/Typealiases.html#/s:9BowOptics4Lensa`; the `Extensions` in the address bar does not need to be present, but it is because the previous page we visited had it in the path. removing it shows the correct page.

3) If you type an operator like `>>>`, it does not show up in the search results.

**Comment by calvellido** [comment]
About point number 1, after scratching my head a bit I discovered that `either` is one of the stop words in the underlining search engine:

https://github.com/olivernn/lunr.js/blob/f9aeea2c592dc08eec67937bcb5b34903e6c04dc/lib/stop_word_filter.js#L72

🤦

I will filter out the ones that could impact Bow definitions.

**Comment by truizlop** [comment]
Interesting. Should we omit completely this stop words list? Potentially any word could end up being part of a method name... What's its purpose in this case?
