### ISSUE TITLE
Create Const missing instances

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#226]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing instances that require to be ported

* Check [Const](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-core-extensions/src/main/kotlin/arrow/core/extensions/const.kt) instances in Arrow repository
* Compare with [Const](https://github.com/bow-swift/bow/blob/master/Sources/Bow/Data/Const.swift) instances in Bow Repository
* Create the missing instances for the existing Typeclasses
* Add the appropriate documentation
* Include test laws for the created instances

At the moment of creating this issue the missing instances are:
- [x] ConstInvariant
- [x] ConstContravariant
- [x] ConstHashable

**Comment by truizlop** [comment]
Const Invariant is automatically conformed from Const Functor. The other two are not applicable at the moment.
