### ISSUE TITLE
Create Monoid missing instances

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#232]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing instances that require to be ported

* Check [Monoid](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-core-extensions/src/main/kotlin/arrow/core/extensions/monoid.kt) instances in Arrow repository
* Compare with [Monoid](https://github.com/bow-swift/bow/blob/master/Sources/Bow/Typeclasses/Monoid.swift) instances in Bow Repository
* Create the missing instances for the existing typeclasses
* Add the appropriate documentation
* Include test laws for the created instances

At the moment of creating this issue the missing instances are:
- [ ] MonoidInvariant

**Comment by truizlop** [comment]
This is not applicable to Bow at the moment.
