### ISSUE TITLE
Port Coproduct missing functions

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#234]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing methods that require to be ported

* Check [Coproduct](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-extras-data/src/main/kotlin/arrow/data/Coproduct.kt) in Arrow repository
* Compare with [Coproduct](https://github.com/bow-swift/bow/blob/master/Sources/Bow/Data/Coproduct.swift) in Bow Repository
* Port the missing functions
* Add the appropriate documentation
* Include tests for the added functions

At the moment of creating this issue the existing differences are:
- [ ] contramap

**Comment by truizlop** [comment]
Added in #347 with the instance of `Contravariant`.
