### ISSUE TITLE
Port Day missing functions

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#236]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing methods that require to be ported

* Check [Day](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-extras-data/src/main/kotlin/arrow/data/Day.kt) in Arrow repository
* Compare with [Day](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-extras-data/src/main/kotlin/arrow/data/Day.kt) in Bow Repository
* Port the missing functions
* Add the appropriate documentation
* Include tests for the added functions

At the moment of creating this issue the existing differences are:
- [ ] mapLazy
- [ ] ap
- [ ] apLazy
- [ ] coflatMapLazy

**Comment by devesh-shetty** [comment]
Could you assign this to me next? Thanks!
cc: @truizlop @miguelangel-dev
