### ISSUE TITLE
Port Kleisli missing functions

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#238]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing methods that require to be ported

* Check [Kleisli](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-extras-data/src/main/kotlin/arrow/data/Kleisli.kt) in Arrow repository
* Compare with [Kleisli](https://github.com/bow-swift/bow/blob/master/Sources/Bow/Arrow/Kleisli.swift) in Bow Repository
* Port the missing functions
* Add the appropriate documentation
* Include tests for the added functions

At the moment of creating this issue the existing differences are:
- [x] liftF
- [x] flatten

**Comment by truizlop** [comment]
`flatten` is part of `Monad`, which `Kleisli` already conforms to.
