### ISSUE TITLE
Port StateT missing functions

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#240]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing methods that require to be ported

* Check [StateT](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-extras-data/src/main/kotlin/arrow/data/StateT.kt) in Arrow repository
* Compare with [StateT](https://github.com/bow-swift/bow/blob/master/Sources/Bow/Transformers/StateT.swift) in Bow Repository
* Port the missing functions
* Add the appropriate documentation
* Include tests for the added functions

At the moment of creating this issue the existing differences are:
- [x] liftF
- [x] inspect
- [x] modify
- [x] modifyF
- [x] setF

**Comment by truizlop** [comment]
`inspect` and `modify` are part of `MonadState`, which `StateT` already conforms to.
