### ISSUE TITLE
Port Validated missing functions

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#241]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing methods that require to be ported

* Check [Validated](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-extras-data/src/main/kotlin/arrow/data/Validated.kt) in Arrow repository
* Compare with [Validated](https://github.com/bow-swift/bow/blob/master/Sources/Bow/Data/Validated.swift) in Bow Repository
* Port the missing functions
* Add the appropriate documentation
* Include tests for the added functions

At the moment of creating this issue the existing differences are:
- [x] orNull
- [x] sequence
- [x] combine

**Comment by truizlop** [comment]
`sequence` is part of `Traverse`, which Validated already conforms to.
