### ISSUE TITLE
Create Cokleisli missing instances

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#248]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing instances that require to be ported

* Check [Cokleisli](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-extras-extensions/src/main/kotlin/arrow/data/extensions/cokleisli.kt) instances in Arrow repository
* Compare with [Cokleisli](https://github.com/bow-swift/bow/blob/master/Sources/Bow/Arrow/Cokleisli.swift) instances in Bow Repository
* Create the missing instances for the existing typeclasses
* Add the appropriate documentation
* Include test laws for the created instances

At the moment of creating this issue the missing instances are:
- [ ] CokleisliContravariant
- [ ] CokleisliProfunctor

**Comment by truizlop** [comment]
These type classes are not applicable at the moment.
