### ISSUE TITLE
Create Coproduct missing instances

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#249]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing instances that require to be ported

* Check [Coproduct](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-extras-extensions/src/main/kotlin/arrow/data/extensions/coproduct.kt) instances in Arrow repository
* Compare with [Coproduct](https://github.com/bow-swift/bow/blob/master/Sources/Bow/Data/Coproduct.swift) instances in Bow Repository
* Create the missing instances for the existing typeclasses
* Add the appropriate documentation
* Include test laws for the created instances

At the moment of creating this issue the missing instances are:
- [x] CoproductHashable
- [x] CoproductContravariant

**Comment by truizlop** [comment]
Hashable not applicable.
