### ISSUE TITLE
Create Ior missing instances

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#251]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing instances that require to be ported

* Check [Ior](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-extras-extensions/src/main/kotlin/arrow/data/extensions/ior.kt) instances in Arrow repository
* Compare with [Ior](https://github.com/bow-swift/bow/blob/master/Sources/Bow/Data/Ior.swift) instances in Bow Repository
* Create the missing instances for the existing typeclasses
* Add the appropriate documentation
* Include test laws for the created instances

At the moment of creating this issue the missing instances are:
- [ ] IorBifunctor 
- [ ] IorHashable

**Comment by truizlop** [comment]
These two instances are unapplicable:
- Bow does not support `Bifunctor` at the moment.
- We still don't have any conformances for `Hashable` for our types.
