### ISSUE TITLE
Create DictionaryK missing instances

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#252]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing instances that require to be ported

* Check [DictionaryK](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-extras-extensions/src/main/kotlin/arrow/data/extensions/mapk.kt) instances in Arrow repository
* Compare with [DictionaryK](https://github.com/bow-swift/bow/blob/master/Sources/Bow/Data/DictionaryK.swift) instances in Bow Repository
* Create the missing instances for the existing typeclasses
* Add the appropriate documentation
* Include test laws for the created instances

At the moment of creating this issue the missing instances are:
- [ ] DictionaryKFunctor
- [ ] DictionaryKFoldable
- [ ] DictionaryKTraverse
- [ ] DictionaryKSemigroup
- [ ] DictionaryKMonoid
- [ ] DictionaryKEq
- [ ] DictionaryKCustomStringConvertible
- [ ] DictionaryKHashable

**Comment by truizlop** [comment]
DictionaryK will probably be removed from the core library and therefore these instances won't be added.
