### ISSUE TITLE
Create SetK missing instances

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#259]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing instances that require to be ported

* Check [SetK](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-extras-extensions/src/main/kotlin/arrow/data/extensions/setk.kt) instances in Arrow repository
* Compare with [SetK](https://github.com/bow-swift/bow/blob/master/Sources/Bow/Data/SetK.swift) instances in Bow Repository
* Create the missing instances for the existing typeclasses
* Add the appropriate documentation
* Include test laws for the created instances

At the moment of creating this issue the missing instances are:
- [ ] SetKCustomStringConvertible
- [ ] SetKFoldable 
- [ ] SetKSemigroupK 
- [ ] SetKMonoidK 
- [ ] SetKHashable

**Comment by truizlop** [comment]
SetK will probably be removed from the core library and therefore these instances won't be added.
