### ISSUE TITLE
Create NonEmptyArray missing instances

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#263]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing instances that require to be ported

* Check [NonEmptyList](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-mtl/src/main/kotlin/arrow/mtl/extensions/nonemptylist.kt) MTL instances in Arrow repository
* Compare with [NonEmptyArray](https://github.com/bow-swift/bow/blob/master/Sources/Bow/Data/NonEmptyArray.swift) instances in Bow Repository
* Create the missing instances for the existing typeclasses
* Add the appropriate documentation
* Include test laws for the created instances

At the moment of creating this issue the missing instances are:
- [ ] NonEmptyArrayFunctorFilter

**Comment by truizlop** [comment]
I think this has been removed from Arrow. In fact, I think NEA cannot have a valid instance for FunctorFilter, as it could end returning an empty array.
