### ISSUE TITLE
Port Comonad missing laws

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#272]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing methods that require to be ported

* Check [Comonad](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-test/src/main/kotlin/arrow/test/laws/ComonadLaws.kt) laws in Arrow repository
* Compare with [Comonad](https://github.com/bow-swift/bow/blob/master/Tests/BowLaws/ComonadLaws.swift) laws in Bow Repository
* Port the missing laws

At the moment of creating this issue the existing differences are:
- [x] cobinding

**Comment by truizlop** [comment]
There is no cobinding implementation in Comonad in Bow at the moment, so this issue is not applicable.
