### ISSUE TITLE
Port Comonad missing functions

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#279]
Related to: #272 

## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing methods that require to be ported

* Check [Comonad](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Comonad.kt) in Arrow repository
* Compare with [Comonad](https://github.com/bow-swift/bow/blob/master/Sources/Bow/Typeclasses/Comonad.swift) in Bow Repository
* Port the missing functions
* Add the appropriate documentation
* Include tests for the added functions

At the moment of creating this issue the existing differences are:
- [ ] cobinding

**Comment by truizlop** [comment]
Implementation of `cobinding` is done in terms of coroutines. At the moment there is no easy translation for this to Swift, so this is left out of the scope.
