### ISSUE TITLE
Port Contravariant missing functions

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#280]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing methods that require to be ported

* Check [Contravariant](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Contravariant.kt) in Arrow repository
* Compare with [Contravariant](https://github.com/bow-swift/bow/blob/master/Sources/Bow/Typeclasses/Contravariant.swift) in Bow Repository
* Port the missing functions
* Add the appropriate documentation
* Include tests for the added functions

At the moment of creating this issue the existing differences are:
- [ ] narrow

**Comment by truizlop** [comment]
According to how variance works in Swift, `narrow` cannot be implemented as part of `Contravariant`.
