### ISSUE TITLE
Port Foldable missing functions

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#282]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing methods that require to be ported

* Check [Foldable](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Foldable.kt) in Arrow repository
* Compare with [Foldable](https://github.com/bow-swift/bow/blob/master/Sources/Bow/Typeclasses/Foldable.swift) in Bow Repository
* Port the missing functions
* Add the appropriate documentation
* Include tests for the added functions

At the moment of creating this issue the existing differences are:
- [ ] iterateRight

**Comment by truizlop** [comment]
`iterateRight` has been deprecated in `Foldable` and move as part of `Eval`. This will be addressed in #298.
