### ISSUE TITLE
Port Functor missing functions

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#283]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing methods that require to be ported

* Check [Functor](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Functor.kt) in Arrow repository
* Compare with [Functor](https://github.com/bow-swift/bow/blob/master/Sources/Bow/Typeclasses/Functor.swift) in Bow Repository
* Port the missing functions
* Add the appropriate documentation
* Include tests for the added functions

At the moment of creating this issue the existing differences are:
- [ ] widen

**Comment by truizlop** [comment]
According to how variance works in Swift, `widen` cannot be implemented as part of `Functor`.
