### ISSUE TITLE
Missing things comparing with Arrow

### ISSUE THREAD

**Issue by victorg1991** [bow-swift/bow#3]
I've made a first pass review of the library to see what is missing and I've found some things

### Optics
- basically everything

### Data
- Sequence

### Free
- FreeApplicative
- Trampoline

### Effects
- Rx

I didn't check in depth to see if there are methods missing yet
@raulraja

**Comment by truizlop** [comment]
Is it necessary to include `Show`? Swift has `CustomStringConvertible`([link](https://developer.apple.com/documentation/swift/customstringconvertible)) which could be used.
