### ISSUE TITLE
Port Index missing functions

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#301]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing methods that require to be ported

* Check [Index](https://github.com/arrow-kt/arrow/blob/master/modules/optics/arrow-optics/src/main/kotlin/arrow/optics/typeclasses/Index.kt) in Arrow repository
* Compare with [Index](https://github.com/bow-swift/bow/blob/master/Sources/BowOptics/Typeclasses/Index.swift) in Bow Repository
* Port the missing functions
* Add the appropriate documentation
* Include tests for the added functions

At the moment of creating this issue the existing differences are:
- [ ] Lens<T, S>.index(i: I)
- [ ] Iso<T, S>.index(i: I)
- [ ] Prism<T, S>.index(i: I)
- [ ] Optional<T, S>.index(i: I)
- [ ] Setter<T, S>.index(i: I)
- [ ] Traversal<T, S>.index(i: I)
- [ ] Fold<T, S>.index(i: I)
- [ ] Lens<T, S>.get(i: I)
- [ ] Iso<T, S>.get(i: I)
- [ ] Prism<T, S>.get(i: I)
- [ ] Optional<T, S>.get(i: I)
- [ ] Setter<T, S>.get(i: I)
- [ ] Traversal<T, S>.get(i: I)
- [ ] Fold<T, S>.get(i: I)

**Comment by truizlop** [comment]
Fixed in #351.
