### ISSUE TITLE
Create Dictionary Optics missing instances

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#307]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing instances that require to be ported

* Check [Map](https://github.com/arrow-kt/arrow/blob/master/modules/optics/arrow-optics/src/main/kotlin/arrow/optics/extensions/map.kt) instances in Arrow repository
* Create `DictionaryOpticsInstances.swift` file in `/BowOptics/Instances` module
* Create the missing instances for the existing typeclasses 
* Add the appropriate documentation
* Include test laws for the created instances

At the moment of creating this issue the missing instances are:
- [ ] DictionaryAt
- [ ] DictionaryTraversal
- [ ] DictionaryEach
- [ ] DictionaryIndex

**Comment by truizlop** [comment]
DictionaryK may be removed as it cannot get any instance for type classes and there is no point on having the wrapper to do nothing. Therefore, these instances will not be added.
