### ISSUE TITLE
Create DictionaryK Optics missing instances 

### ISSUE THREAD

**Issue by Tylos** [bow-swift/bow#308]
## Description

In order to align Bow and [Arrow](https://github.com/arrow-kt/arrow) API, there are some missing instances that require to be ported

* Check [MapK](https://github.com/arrow-kt/arrow/blob/master/modules/optics/arrow-optics/src/main/kotlin/arrow/optics/extensions/mapk.kt) instances in Arrow repository
* Create `DictionaryKInstances.swift` file in `/BowOptics/Instances` module
* Create the missing instances for the existing typeclasses 
* Add the appropriate documentation
* Include test laws for the created instances

At the moment of creating this issue the missing instances are:
- [ ] DictionaryKAt
- [ ] DictionaryKEach
- [ ] DictionaryKFilterIndex
- [ ] DictionaryKIndex

**Comment by truizlop** [comment]
DictionaryK is not adding too much value in Bow as it cannot provide instances to most of the type classes and will probably be removed. Therefore, these instances are not being added.
