### ISSUE TITLE
Include Async law - Bracket release is called on completedOrError

### ISSUE THREAD

**Issue by miguelangel-dev** [bow-swift/bow#324]
## Description

Update to the definition of the [type class in Arrow](https://github.com/arrow-kt/arrow/blob/master/modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/typeclasses/Async.kt). See its [type class laws](https://github.com/arrow-kt/arrow/blob/b5746f09d505a53b77f5aa6b247b01536ab45045/modules/core/arrow-test/src/main/kotlin/arrow/test/laws/AsyncLaws.kt).

## Modules

- `BowEffectsLaws`.

## Dependencies

- `Promise`

**Comment by truizlop** [comment]
As Promise won't be part of this module at the moment, there is no need for this.
