### ISSUE TITLE
Add fastlane to automate release process

### ISSUE THREAD

**Issue by victorg1991** [bow-swift/bow#36]

**Comment by devesh-shetty** [comment]
👋 
I'll be working on this!

**Comment by miguelangel-dev** [comment]
Ey @devesh-shetty!!

Nice to see you here! If you need to be familiar with `Bow` modules and some of the dependency managers maybe will be easier for your start from that issue #447

To give you more details about release process, in each release, we need to do the next tasks:
- Update `Podfile`, `Package.swift` and `Cartfile` [manual]
- Update `Documentation` and its dependencies (it works with CocoaPods) [manual]
- Update the `podspec` [manual]

- Generate the tags of the new version from `master` branch [to be automated]
- Propagate to [CocoaPod](https://cocoapods.org/) the Bow modules using the podspecs [to be automated]

I have added information which steps should be automated :)

**Comment by devesh-shetty** [comment]
Awesome, thanks for the detailed information @miguelangel-dev

**Comment by devesh-shetty** [comment]
> Launch an internal mail/slack/gitter message with the details of the new Bow version 

This is the only thing left to be automated

**Comment by truizlop** [comment]
Do you need any info to complete this task?

**Comment by devesh-shetty** [comment]
There seems to no supported gitter action from [fastlane](https://docs.fastlane.tools/actions/#notifications)
<img width="819" alt="Screen Shot 2019-10-16 at 4 15 12 AM" src="https://user-images.githubusercontent.com/16123698/66900871-9644c680-efcb-11e9-8f15-18cba2d0e7f4.png">

I'll have to create one!

**Comment by devesh-shetty** [comment]
> Do you need any info to complete this task?

Is there a slack channel you'd like to post to?
I am still working on creating a gitter action to post messages on release.

**Comment by miguelangel-dev** [comment]
Sounds great! Thanks for your work on creating a Gitter action! 

About `Slack` is nice to know it has a smooth integration, but for now, as we do not have an official, I think it can wait :)

**Comment by truizlop** [comment]
We did last release using `fastlane` and it worked nicely, except for a side issue: Cocoapods takes some time to process pods after a push, so when we need to push something that depends on some other pod that was just pushed, it fails and we have to reattempt it after several minutes. This is a different issue though, so I could say this can be considered done.

**Comment by devesh-shetty** [comment]
> We did last release using `fastlane` and it worked nicely, except for a side issue: Cocoapods takes some time to process pods after a push, so when we need to push something that depends on some other pod that was just pushed, it fails and we have to reattempt it after several minutes. This is a different issue though, so I could say this can be considered done.

Ah I wonder what could be done for that.

Quick question: Is CHANGELOG.next file not helpful?
