### ISSUE TITLE
Website issues

### ISSUE THREAD

**Issue by truizlop** [bow-swift/bow#427]
## Description

There are several issues with the website that needs to be fixed before the new release:

- [ ] Version 0.5.0 (current) appears twice, both in `Documentation` and in `API reference`.
- [ ] Clickng on `API Reference` > last option leads to a 404 page.
- [ ] In `API Reference` > `next` there are some new artifacts that are not present. For instance, the new Effects module includes type classes like `Concurrent` or `UnsafeRun`, or data types like `Atomic` or `Ref` that do not appear there.
- [ ] Every time we merge a PR, there is a file at the location `/vendor/bundle/ruby/2.4.0/gems/ffi-1.9.25/ext/ffi_c/libffi-x86_64-darwin18/include/ffitarget.h` that gets added and prevents the automatic deploy of the page to GitHub pages. We have tried adding it to the `.gitignore` with no success. Currently we need to delete it manually after every merge.

**Comment by calvellido** [comment]
First one is expected behaviour. It can be changed here:

https://github.com/bow-swift/bow/blob/cdca130239820fa5254888ae5707bc3367cc9d73/scripts/gen-docs.rb#L15

**Comment by calvellido** [comment]
For the rest of them, I'd say that are mostly related to the last point. That file preventing the deployment is what makes the site not being properly updated, while the content in the `gh-pages` branch is correct :man_facepalming:

**Comment by calvellido** [comment]
Sad thing is that I already had a look into it and wasn't able to conclude/fix what was causing it, most probably the Travis macOS build environemnt. Anyway, I will investigate further to try to set a solution for this.
