### ISSUE TITLE
Add Semiring type class

### ISSUE THREAD

**Issue by truizlop** [bow-swift/bow#448]
## Description

Add `Semiring` type class together with its laws.

Links in Arrow:
- [Semiring](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Semiring.kt)
- [SemiringLaws](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-test/src/main/kotlin/arrow/test/laws/SemiringLaws.kt)

## Modules

- Bow (core)

**Comment by iboss-ptk** [comment]
I would love to have a take on this :D

**Comment by iboss-ptk** [comment]
Also I am thinking of adding it's law check to something. Does that make sense to also give an instance of `Semiring` to the collections (not sure about Dictionary, haven't think about it yet but if I can law check it then it should work)

**Comment by truizlop** [comment]
The most straightforward types to add conformance to Semiring are numeric types (`Int`, `UInt`, `Double`, `Float`), as they already have conformance to Semigroup and Monoid. You can find them in [`Sources/Bow/Instances/NumberInstances.swift`](https://github.com/bow-swift/bow/blob/master/Sources/Bow/Instances/NumberInstances.swift). If you have any questions on how to proceed with this, let us know. Thanks for your interest!
