### ISSUE TITLE
Add Semigroupal type class

### ISSUE THREAD

**Issue by truizlop** [bow-swift/bow#449]
## Description

Add `Semigroupal` type class together with its laws.

Links in Arrow:
- [Semigroupal](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Semigroupal.kt)
- [SemigroupalLaws](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-test/src/main/kotlin/arrow/test/laws/SemigroupalLaws.kt)

## Modules

- Bow (core)

**Comment by devesh-shetty** [comment]
Could you assign this to me next? Thanks!

**Comment by devesh-shetty** [comment]
PR didn't auto-close the ticket 🤔 
I believe this is good to close now!
