### ISSUE TITLE
Add Monoidal type class

### ISSUE THREAD

**Issue by truizlop** [bow-swift/bow#450]
## Description

Add `Monoidal` type class together with its laws.

Links in Arrow:
- [Monoidal](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Monoidal.kt)
- [MonoidalLaws](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-test/src/main/kotlin/arrow/test/laws/MonoidalLaws.kt)

## Modules

- Bow (core)

**Comment by devesh-shetty** [comment]
Could you assign this to me next?

**Comment by truizlop** [comment]
Done, thanks!
