### ISSUE TITLE
Add Divide type class

### ISSUE THREAD

**Issue by truizlop** [bow-swift/bow#451]
## Description

Add `Divide` type class together with its laws.

Links in Arrow:
- [Divide](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Divide.kt)
- [DivideLaws](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-test/src/main/kotlin/arrow/test/laws/DivideLaws.kt)

## Modules

- Bow (core)

**Comment by devesh-shetty** [comment]
Could you assign this to me next? Thanks!
