### ISSUE TITLE
Add Divisible type class

### ISSUE THREAD

**Issue by truizlop** [bow-swift/bow#452]
## Description

Add `Divisible` type class together with its laws.

Links in Arrow:
- [Divisible](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-core-data/src/main/kotlin/arrow/typeclasses/Divisible.kt)
- [DivisibleLaws](https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-test/src/main/kotlin/arrow/test/laws/DivisibleLaws.kt)

## Modules

- Bow (core)

**Comment by devesh-shetty** [comment]
Could I take this up next? Thanks!

**Comment by miguelangel-dev** [comment]
Resolve in #465
