### ISSUE TITLE
["Request"] Tree data type

### ISSUE THREAD

**Issue by ferranpujolcamins** [bow-swift/bow#612]
## Description

A tree data type like https://hackage.haskell.org/package/containers-0.6.4.1/docs/Data-Tree.html

## Modules

Bow

## Breaking changes

No, new data type.

**Comment by truizlop** [comment]
Looks good to me. Do you want to take it?

**Comment by ferranpujolcamins** [comment]
Yeah!

**Comment by truizlop** [comment]
Closed by #626
