### ISSUE TITLE
["Bug"] I lost `BowGeneric` Modules

### ISSUE THREAD

**Issue by CrystalBlack** [bow-swift/bow#613]
I use Swift Package Manager in Xcode 12.
I cant add `BowGeneric` Modules to my lib list. 
Because i have no `BowGeneric` Modules.

This is all the list of the modules I can choose from Xcode lib list：
Bow
BowEffects
BowEffectsGenerators
BowEffectsLaws
BowFree
BowFreeGenerators
BowGenerators
BowLaws
BowOptics
BowOpticsLaws
BowRecursionSchemes
BowRx
BowRxGenerators

**Comment by truizlop** [comment]
Thanks for reporting this. I'll investigate and come back to you. Has this worked before fo you using SPM?

**Comment by CrystalBlack** [comment]
Use pod , it worked.
Seemingly, your `package.swift` file lost `BowGeneric` lib.

**Comment by truizlop** [comment]
I noticed that, I am working on a fix. You'll need to depend on `master` for a while until we release a new version.

**Comment by CrystalBlack** [comment]
Thanks……
