### ISSUE TITLE
Documentation for simulated rank-n polymorphism (aka documentation on FunctionK)

### ISSUE THREAD

**Issue by ferranpujolcamins** [bow-swift/bow#620]
## Description

FunctionK allows us to create a class that encapsulates a polymorphic function, thus simulating a closure that is polymorphic on some of its type parameters (rank-n polymorphism). We should add a documentation page explaining this technique.

We should add some example and cover some topics like polymorphic type parameters vs bound type parameters.

## Modules

Documentation

## Breaking changes

None

**Comment by truizlop** [comment]
Agreed. Do you have something in mind? A draft or something?

**Comment by ferranpujolcamins** [comment]
Yeah, I'll try to come up with something.

**Comment by truizlop** [comment]
Sounds good to me. I'm assigning this to you.

**Comment by truizlop** [comment]
Closed by #622
