### ISSUE TITLE
["Request"] Add conversion from Foldable to ArrayK

### ISSUE THREAD

**Issue by ferranpujolcamins** [bow-swift/bow#631]
## Description

Any Foldable type can be converted to an `ArrayK`. Right now there's no method in the `Foldable` api that suggests this is possible, so people that is new to `Foldable` might not realize that `foldMap { ArrayK($0) }` gives you an array.

I propose to add an `asArray()` method to `Foldable` that builds an `ArrayK` from the foldable.

I also suggest to add a new constructor to `ArrayK` that takes a `Foldable` and does the same. This is how you transform any sequence to an Array on the standard library, so I think it's good to be consistent with that too.

This brings no new possibilities, but I think helps people get familiar with Foldable, and provides a shortcut for situations when "I just want an array".

## Modules

Bow

## Breaking changes

No

**Comment by truizlop** [comment]
Looks good to me!
