### ISSUE TITLE
Question: How to connect Lens which has optional value?

### ISSUE THREAD

**Issue by haifengkao** [bow-swift/bow#656]
suppose I have the following structures:
```
struct Handle: AutoLens  {
}

struct Door: AutoLens  {
   var handle: Handle?
}

struct Car: AutoLens {
    var door: Door?
}
```

I can use `Car.lens(for: \.door)` to get `Lens<Car, Door?>`
`Door.lens(for: \.handle)` to get `Lens<Door, Handle?>`

but when I connect the two
`Car.lens(for: \.door)` + `Door.lens(for: \.handle)` 
the compiler will tell me type mismatch

How do I connect these lens?

**Comment by truizlop** [comment]
When you have a field that has an optional type, there is an optic to address this fact. You can look for `Optional` (in the last released version), which has been renamed to `AffineTraversal` in the next release we will do.

You can check the documentation of [how to write your own `AffineTraversal`/`Optional`](https://bow-swift.io/docs/optics/writing-your-own-optics/) and [how to get it automatically]. Also, we have [documented its API](https://bow-swift.io/api-docs/Extensions/AffineTraversal.html).

In your particular example, and using Bow 0.8.0, it would be something like:

```swift
struct Handle: AutoOptional  {}

struct Door: AutoOptional {
   var handle: Handle?
}

struct Car: AutoOptional {
    var door: Door?
}

Car.optional(for: \.door) + Door.optional(for: \handle)
```

**Comment by haifengkao** [comment]
thanks 😘
