### ISSUE TITLE
"ap" is backwards?

### ISSUE THREAD

**Issue by stephencelis** [bow-swift/bow#77]
Swift can define `ap` in a much more readable (left-to-right, non-nested) format that matches Haskell. By introducing a generic at function scope we can constrain `F`'s `A` to be a function between generics:

``` diff
-public func ap<B>(_ ff: F<(A) -> B>) -> F<B>
+public func ap<A1, B>(_ fa: F<A1>) -> F<B> where A == (A1) -> B
```

And in practice:

``` swift
Option.pure(add).ap(one).ap(two)

// vs. the right-to-left, awkwardly nested:
two.ap(one.ap(Option.pure(add)))
```

FWIW many functional libraries in Swift introduce the `<*>` operator, as another option. That could be an alternate consideration if the inconsistency with Arrow is an issue, though I assume Bow should be optimized for Swift syntax in general.

**Comment by truizlop** [comment]
The definition of `ap` is done to keep consistency with the typeclass definition for `Applicative`, and the behavior of `ap` is not the same as in `<*>`. If we check the signature for both:

```swift
ap : (F<A>, F<(A) -> B>) -> F<B>
<*> : (F<A>, F<B>) -> F<(A) -> B>
```

`<*>` definition, and the usage you are proposing, is encoded in Bow as `product` in the `Applicative` typeclass, and the way you could be using it is:

```swift
Option<Int>.applicative().product(one, two).fix().map(add)
```

The syntax could be better but it is a matter of getting to the point where the language supports higher kinded types natively.

**Comment by stephencelis** [comment]
It may be a language barrier thing, but you have me a bit confused. You don't have `<*>` defined at all in Bow, so there's no signature to compare your `ap` with. You've also mentioned deprecating operators, so I assume `<*>` isn't being added?

In Haskell, `ap` is on the `Monad` typeclass and is defined with the exact same infix way as `<*>` (though with different type class constraints):

``` h
ap :: m (a -> b) -> m a -> m b
<*> :: f (a -> b) -> f a -> f b
```

So is it fair to assume that you want Bow's type classes to be consistent with _Arrow's_? That can definitely be a project prerogative, though porting over a language limitation is unfortunate.

**Comment by truizlop** [comment]
Sorry, I think I misunderstood it on my first read. You are right; in fact, in Cats for Scala this is reversed as well. Since your approach is more readable in Swift, we can refactor it for the sake of the usability. Our aim is to maximize compatibility with Arrow, of course, but in some cases like this, a more Swiftier approach is preferrable. I'll add this to my pipeline and perform the change in the next few days.

**Comment by truizlop** [comment]
@stephencelis please, take a look at the changes in #80, addressing the improvement you suggested here.
