### ISSUE TITLE
Operator issues

### ISSUE THREAD

**Issue by stephencelis** [bow-swift/bow#78]
A few issues with how Bow uses operators:

- All the custom operators introduced use the same precedence group that ships with Swift (`AdditionPrecedence`). This prevents them from playing nicely with one another. For example, a Kleisli chain with pure compositions requires parenthesizing when `>>>` should take precedence over `>=>`.
    ``` swift
    f
      >>> impureG
      >=> pureH
      >>> impureI
      >=> impureJ
    ```

- Data defines `infix operator >>=`, but Swift already ships with `>>=` for bitwise shift assignment. Swift libraries tend to define `>>-` or `>>>=` instead as a result. In general, `>>=` seems less useful in Swift because you can define `flatMap` as an infix method, preserving readability where bind creates nesting.

- Optics overloads `+` for composition. It might make more sense to use `<<<` or introduce a new operator. PureScript's profunctor package once defined `..`, though they use plain-ole `<<<` these days.

**Comment by truizlop** [comment]
Operators are always a matter of discussion, controversy and readability problems, and for those reasons we are thinking about deprecating most of them, specially `>>=` and `>=>`, given that they are not generically defined (they need a `Monad` instance in order to be generic aliases of `flatMap` or Kleisli composition). As for the use of `+` to compose optics, this is a convention to maintain compatibility with Arrow, but definitely can be discussed and changed in the future.

**Comment by nomisRev** [comment]
@truizlop
> As for the use of + to compose optics, this is a convention to maintain compatibility with Arrow, but definitely can be discussed and changed in the future.

They're also up for discussion in Arrow-Optics if they cause any confusion or controversy. I added them in the beginning but have personally not used them and could be considered deprecated in favor of a more streamlined core package with the DSL support for a slicker API.

**Comment by stephencelis** [comment]
I think it's appropriate to omit them, especially the overloads on `+` and `>>=`, which can hurt error messaging, compile times, and diagnostics. While I appreciate operators, personally, they are definitely a controversial topic, and Bow could always quarantine controversy to a `BowOperators` module.

**Comment by truizlop** [comment]
I completely agree with that. Thanks for your suggestion!

**Comment by truizlop** [comment]
#81 Operators `>>=` and `>=>` have been marked as deprecated and will be completely removed in a couple of versions. Regarding the operators for optics composition, the actual operator is not changed until a decision is made. We will postpone moving them to another module.
